-- =========================================================
-- DATABASE SCRIPT - MiR250 PROJECT
-- Supabase / PostgreSQL
-- Structure only, without sample data
-- =========================================================

-- Drop tables in the correct order because of foreign keys
DROP TABLE IF EXISTS mission_histories CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS n8n_chat_histories CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS missions CASCADE;
DROP TABLE IF EXISTS data CASCADE;

-- =========================================================
-- TABLE: missions
-- Stores the robot missions and their associated goals
-- =========================================================

CREATE TABLE missions (
    guid VARCHAR PRIMARY KEY,
    goal VARCHAR NOT NULL UNIQUE
);

-- =========================================================
-- TABLE: products
-- Stores the available products in the warehouse
-- Each product is associated with a goal/location
-- =========================================================

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    goal VARCHAR NOT NULL,

    CONSTRAINT fk_products_missions
        FOREIGN KEY (goal)
        REFERENCES missions(goal)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- =========================================================
-- TABLE: orders
-- Stores the orders created from the chat
-- =========================================================

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    data JSON,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================
-- TABLE: mission_histories
-- Stores the missions sent to the robot
-- and links them to an order
-- =========================================================

CREATE TABLE mission_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state TEXT,
    mission_queue_id NUMERIC,
    order_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_mission_histories_orders
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- =========================================================
-- TABLE: data
-- Stores periodic robot status metrics
-- =========================================================

CREATE TABLE data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    battery NUMERIC,
    mission_text TEXT,
    state VARCHAR,
    velocity_linear NUMERIC,
    velocity_angular NUMERIC
);

-- =========================================================
-- TABLE: n8n_chat_histories
-- Stores the n8n chat history
-- =========================================================

CREATE TABLE n8n_chat_histories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR NOT NULL,
    message JSONB NOT NULL
);